version: "3.1"

networks:
  transaction_network:
    ipam: #IP Address Management.
      config:
        - subnet: 100.10.0.0/16

services:
    mysql:
      image: mysql:5.7
      container_name: mysql_transaction
      working_dir: /var/lib/mysql
      volumes:
        - ./mysql/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_TCP_PORT=${MYSQL_PORT}
      ports:
        - "${MYSQL_PORT}:${MYSQL_PORT}"
      expose:
        - "${MYSQL_PORT}"
      networks:
        transaction_network:
          ipv4_address: 100.10.0.11

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin_transaction
      links:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_PORT: ${MYSQL_PORT}
      ports:
        - ${PHPMYADMIN_PORT}:80
      networks:
        transaction_network:
          ipv4_address: 100.10.0.12

    nginx:
      image: nginx
      container_name: nginx_transaction
      working_dir: /transaction
      volumes:
        - ../:/transaction
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/api.conf:/etc/nginx/sites-enabled/api.conf
      extra_hosts:
        - "php_transaction:100.10.0.14"
      ports:
        - "${NGINX_PORT}:80"
      networks:
        transaction_network:
          ipv4_address: 100.10.0.13

    php:
      build: ./php
      container_name: php_transaction
      volumes:
        - ../:/transaction
        - ./php/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      networks:
        transaction_network:
          ipv4_address: 100.10.0.14